### ISSUE TITLE
在国外vps docker-compose部署的，提问会显示{   "error": true,   "message": "Load failed" } 是咋回事

### ISSUE THREAD

**Issue by zcracker** [nashsu/FreeAskInternet#1]

**Comment by Rogarliu** [comment]
我也是报错
freegpt35_1         | Error refreshing session ID, retrying in 1 minute...
freegpt35_1         | If this error persists, your country may not be supported yet.
freegpt35_1         | If your country was the issue, please consider using a U.S. VPN.
freegpt35_1         | Error refreshing session ID, retrying in 1 minute...
freegpt35_1         | If this error persists, your country may not be supported yet.
freegpt35_1         | If your country was the issue, please consider using a U.S. VPN.
freegpt35_1         | 💡 Server is running at http://localhost:3040
freegpt35_1         | 
freegpt35_1         | 🔗 Base URL: http://localhost:3040/v1
freegpt35_1         | 🔗 ChatCompletion Endpoint: http://localhost:3040/v1/chat/completions
freegpt35_1         | 
freegpt35_1         | 📝 Original TS Source By: Pawan.Krd
freegpt35_1         | 📝 Modified Into JavaScript By: Adam
freegpt35_1         | 
freegpt35_1         | Error refreshing session ID, retrying in 1 minute...
freegpt35_1         | If this error persists, your country may not be supported yet.
freegpt35_1         | If your country was the issue, please consider using a U.S. VPN.

**Comment by ymg2007** [comment]
我也是这个报错
![chrome_K4vMJKyJ3g](https://github.com/nashsu/FreeAskInternet/assets/24608776/2c7e28d7-9184-44dc-a5c7-7dd347e19a31)
wozheg
求解决

**Comment by duronxx** [comment]
me too 
![image](https://github.com/nashsu/FreeAskInternet/assets/33643555/648448aa-1e53-4c2c-8794-d5a39a3a517a)

**Comment by haso2007** [comment]
when I install in the synology docker, it show the same as above message
