### ISSUE TITLE
通过代理无法访问

### ISSUE THREAD

**Issue by 2996637314** [nashsu/FreeAskInternet#25]
服务器中已经安装梯子 服务器本身可以访问openai 在docker中配置了代理 无法访问 
![image](https://github.com/nashsu/FreeAskInternet/assets/56195340/d3bda401-fe25-4ded-bb74-95b37bc2f289)

**Comment by pch9520** [comment]
一样，配置了proxy但接口还是调不通
<img width="1027" alt="image" src="https://github.com/nashsu/FreeAskInternet/assets/43515614/d23efa0f-db0c-45bd-a14f-9ee17190fe8e">

**Comment by nashsu** [comment]
新版更新了，大家可以更新下，不光GPT3.5，kimi、Qwen、智谱GLM、自定义LLM都支持了。
彻底解决这个问题

**Comment by k0286** [comment]
@nashsu 可以詳細解釋一下代理如何配置嗎?

目前針對各服務修改了以下配置，仍無法正常運作

`backend`: 增加`HTTPS_PROXY`環境變數

`llm-*`: 增加`HTTPS_PROXY`和`HTTP_PROXY`環境變數

`searxng`: 修改` ./searxng/settings.yml`設定`outgoing: proxies : `
