### ISSUE TITLE
花钱买star了?短短几天怎么这么多星

### ISSUE THREAD

**Issue by Moeary** [nashsu/FreeAskInternet#27]
莫名其妙出现在trend里面 然后一堆issue又证明这玩意跑不起来,现在openAI都可以免注册网页使用GPT3.5 turbo了你这个项目还有什么价值吗
![image](https://github.com/nashsu/FreeAskInternet/assets/103913682/a8899dd3-859c-42c4-8161-b0622c630171)

**Comment by 907739769** [comment]
可以用  
![image](https://github.com/nashsu/FreeAskInternet/assets/27858369/76d3cc60-66d3-4437-9abc-0e73dd5c8518)

**Comment by sparkssssssss** [comment]
> 可以用 ![image](https://private-user-images.githubusercontent.com/27858369/320906315-76d3cc60-66d3-4437-9abc-0e73dd5c8518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTc5MDYsIm5iZiI6MTcxMjcxNzYwNiwicGF0aCI6Ii8yNzg1ODM2OS8zMjA5MDYzMTUtNzZkM2NjNjAtNjZkMy00NDM3LTlhYmMtMGU3M2RkNWM4NTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNDAwYjMyYjk1YjYxNmI0NGQ3YjFiMTAwYzc0ZGI3NjIyY2I5NzZkNDIyZGZjZTliNjQxZjljZTk3NjBmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BT_tkQUGUPOpDSPEm2GLbEuvL8vNwYzWYQKfzqZD5sA)

请教下,我docker-compose up 以后,可以访问,但是提问还是普通的3.5,不会联网,还需要配置什么吗

**Comment by zsychn** [comment]
@907739769 我的只有链接，好奇怪

**Comment by nashsu** [comment]
大家质疑很正常，至于花钱买流量，肯定是没有，也没有意义。流量来源有很多旁证，比如我的推特，和推特相关推文的曝光率、转发率和被大v的曝光，同时我一开始也很明确就是一个对产品、增长黑客和AI的一个实验。

我后面也会写复盘，到时候会也会共享出来。
