### ISSUE TITLE
Please setup the output to "English"

### ISSUE THREAD

**Issue by Tikam02** [nashsu/FreeAskInternet#33]
## The output chats are in chinese

![image](https://github.com/nashsu/FreeAskInternet/assets/10548085/3a3bd050-688e-474e-b6a5-266dbe46141c)

**Comment by ibrahimkettaneh** [comment]
I would like to boost this

**Comment by ibrahimkettaneh** [comment]
duplicate of #16

**Comment by nashsu** [comment]
Just update, add new UI interface, you can set response language, and custom LLM setting.
