### ISSUE TITLE
我部署成功了，希望可以在首页加个广告位

### ISSUE THREAD

**Issue by haolixu** [nashsu/FreeAskInternet#39]
作者可以告诉我怎么实现吗，我比较菜不知道咋实现，我会给你推广项目，有收入了就捐赠

**Comment by wyt990** [comment]
你的能正常返回吗？我的部署了返回不了信息。

**Comment by haolixu** [comment]
> 你的能正常返回吗？我的部署了返回不了信息。

我是用的国外服务器  部署很简单
