### ISSUE TITLE
20240410_18:00升级后，会出现没有查询结果的情况

### ISSUE THREAD

**Issue by wyt990** [nashsu/FreeAskInternet#40]
已有梯子
![微信图片_20240410183940](https://github.com/nashsu/FreeAskInternet/assets/86013697/c9f1424b-4c75-4a04-bd03-8686e2f287ff)
![微信图片_20240410184045](https://github.com/nashsu/FreeAskInternet/assets/86013697/a21cb13f-9862-44a6-aa4b-fe6f95449aac)

**Comment by wyt990** [comment]
需要配置token吗？我看介绍说什么都不用配置就能用。所以还没有配置token。

**Comment by nashsu** [comment]
如果使用 kimi、Qwen、ZhipuAI，需要配置token，但是就不需要翻墙了。

**Comment by csccoder** [comment]
token怎么配置呢。我看了这篇获取token的指南https://github.com/LLM-Red-Team，获取并配置了token ，还是显示搜索失败

**Comment by lonngxiang** [comment]
![image](https://github.com/nashsu/FreeAskInternet/assets/40717349/8c771a78-9151-41df-82db-244d2553b8d2)
搜索失败
