### ISSUE TITLE
本地部署不能正常使用

### ISSUE THREAD

**Issue by ChinaArJun** [nashsu/FreeAskInternet#5]
{
  "error": true,
  "message": "network error"
}

**Comment by nashsu** [comment]
请确认是否docker服务都正常启动，这个报错是因为无法访问到后台接口

**Comment by ChinaArJun** [comment]
好吧，服务报错需要用 vpn，
（Error refreshing session ID, retrying in 1 minute...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN.）

所以这个是必须部署在国外的环境吧

**Comment by funisgoou** [comment]
![image](https://github.com/nashsu/FreeAskInternet/assets/43173604/3cb77da0-ee72-4b0b-b88d-43aef8fa6f82)
我也是用不了，这是为什么呢？我明明挂了VPN能正常浏览国外网络。

**Comment by benhot** [comment]
> ![image](https://private-user-images.githubusercontent.com/43173604/320192187-3cb77da0-ee72-4b0b-b88d-43aef8fa6f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTkyNDEsIm5iZiI6MTcxMjU1ODk0MSwicGF0aCI6Ii80MzE3MzYwNC8zMjAxOTIxODctM2NiNzdkYTAtZWU3Mi00YjBiLWI4OGQtNDNhZWY4ZmE2ZjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NGJjMzgyYjJlMjUyOGVmNzQ3N2NkODk1NTJjMjU4YTdkMTkyMDc5MjRmNTIyZGI4ODJhZTNlM2ZiNGVkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vjTdByniDk6ItCy3XpRF_2omzrfaBu6xFxF-J-ZZfS8) 我也是用不了，这是为什么呢？我明明挂了VPN能正常浏览国外网络。

同样的问题

**Comment by wolfg1969** [comment]
看看 backend 容器的日志里有没有访问 searxng 服务 403 错误

**Comment by ChinaArJun** [comment]
目前部署到国外服务器可以正常使用了，本地部署应该需要设置代理
