### ISSUE TITLE
项目运行后请求报错

### ISSUE THREAD

**Issue by evilvlso** [nashsu/FreeAskInternet#6]
docker有设置http_proxy, 在searxng容器内请求query.wikidata.org是可以的，但正常运行对话会有如图的报错
大佬，是我的网络问题么？

<img width="762" alt="image" src="https://github.com/nashsu/FreeAskInternet/assets/25767862/fd4b6c8e-ccf3-4751-b095-3e6712bc289b">

**Comment by nashsu** [comment]
看报错应该还是网络问题
