### ISSUE TITLE
问下GPT 是如何查询searxng的返回结果的？

### ISSUE THREAD

**Issue by jinwyp** [nashsu/FreeAskInternet#9]
1. 问下GPT 是如何查询searxng的返回结果的？是用了类似RAG的技术吗？ 还是有什么简单的方法？
2. 还有 searxng查询的结果会缓存吗？ 

看了下 searxng项目 searxng的搜索网络的结果好像是保存在redis里面

**Comment by nashsu** [comment]
1. searxng有API接口，可以直接以json格式返回搜索结果。
2. 用trafilatura获取搜索结果URL的主要内容，将这些内容通过prompt给到LLM回答用户问题。
3. 目前没做缓存，searxng内部自己有没有没有仔细研究。
